name: Pulumi
on:
  push:
    branches:
      - main
permissions:
  contents: 'read'
  id-token: 'write'
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: package.json
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      # - name: gcloud
      #   run: gcloud services list
      - name: NPM Install
        run: npm install
      - name: Run Pulumi
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: team-ce/lotctl
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
